name: Ruby-rspec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test with Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
          - '2.6'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      
      - name: "Run Linters"
        run: bundle exec rubocop

      - name: Build and test with rspec
        run: bundle exec rspec
